### ISSUE TITLE
Where is "splits/"?

### ISSUE THREAD

**Issue by CSer-Tang-hao** [dvornikita/fewshot_ensemble#1]
The issue as shown in the title, Looking forward to hearing from you!

**Comment by dvornikita** [comment]
Hello,

Can you tell me what command you are running?

**Comment by CSer-Tang-hao** [comment]
> 你好，
> 
> 您能告诉我您正在运行什么命令吗？

i want to train a ResNet18 on mini-ImageNet by using a single model, i find your code didn‘t provide  splits and datasets, when i  try to solve this issue successfully,   another problem happen again!:

File "/data/Code/Few-shot/fewshot_ensemble/models/losses.py", line 17, in train_loss_fn
    loss = F.nll_loss(log_p_y, labels, reduction='mean')
    return torch._C._nn.nll_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index)
    raise ValueError(reduction + " is not a valid value for reduction")
ValueError: mean is not a valid value for reduction

**Comment by dvornikita** [comment]
What version of pytorch are you using?

**Comment by dvornikita** [comment]
You are right about the splits. Sorry about that. I'll upload it now.

**Comment by CSer-Tang-hao** [comment]
> What version of pytorch are you using?

The version of my PyTorch is 0.4.1, and the version of my python is 3.6.0, I have solved the above issues by deleting "reduction='mean' ", only using " loss = F.nll_loss(log_p_y, labels) ". 
I also find in your code "./singles/train.py", you use the value of "val_loss" to save best_model instead of  the value of "val_acc", I think this  is not suitable, because I find the value of  "val_acc" is not best when the value of "val_loss" is smaller in the experiments.

**Comment by dvornikita** [comment]
Updating pytorch to 1+ version will solve the issue with rediction=mean.

As for the val_acc/val_loss, you are right. I have changed my checkpointing scheme for ensembles but forgot to do that for the single model training. Do you want to do a pull request?

Best,
Nikita

**Comment by CSer-Tang-hao** [comment]
> Updating pytorch to 1+ version will solve the issue with rediction=mean.
> 
> As for the val_acc/val_loss, you are right. I have changed my checkpointing scheme for ensembles but forgot to do that for the single model training. Do you want to do a pull request?
> 
> Best,
> Nikita

Recently, I am revisiting and running this code. I also found 2 mistakes:
(1) ./singles/config.py#L130~L131 should be removed, otherwise compiling "config.py" will report an error
(2) ./data/data_utils.py#L58: if backbone == 'deep', the resize shouldn't be 'None', otherwise it will report the error about the transformation of the input image. I think it should resize to 256 firstly, then crop to 224! 

The randomness of the results was too great! I use the same best_model to test with 5-ways 5 shot twice, firstly I get "76.38 +/- 0.47", secondly I get "77.26 +/- 0.46". It is incredible !

**Comment by dvornikita** [comment]
Thank you for the notes. I'll fix that asap.

As for the variance in the results, this is a property of the evaluation protocol, not the method. To reduce this effect when evaluating, run the tasting with the flag `--determ`. It will set a random seed and ensure deterministic behavior. By doing so you can compare different models in a fair way.
