### ISSUE TITLE
ValueError: Sample larger than population

### ISSUE THREAD

**Issue by shivamsaboo17** [dvornikita/fewshot_ensemble#3]
Getting this error from meta_dataset.py file

```python
chosen_class_inds = random.sample(
                all_class_inds, self.n_train + self.n_test)
```

I am training a single model on cub dataset. Do you know what might be causing this?

Values of self.n_train -> 15, self.n_test -> 5, len(all_class_inds) -> 30

**Comment by dvornikita** [comment]
Hi, 

Could you please give me the command you are running and the full error trace?

Also, how do you know that the "Values of self.n_train -> 15, self.n_test -> 5, len(all_class_inds) -> 30"? Did you check this with a debugger/print or those are the intended values?

**Comment by shivamsaboo17** [comment]
Hi @dvornikita , thanks for quick reply. The code is working now. I created non overlapping class wise splits in train, val and test csv for cub dataset (random splitting of classes). I had a question however, 

I was training a single model using the command:
```
python singles/train.py --model.model_name=wideresnet --data.dataset=cub --model.backbone=wide 
```
Now as my splits are non overlapping in train, validation and test set (which is the case in few shot learning), can you please tell me how is the validation accurracy computed in this single model as classes in training and validation set will be different? Are you using distance based classifier in single model as well and computing embedding vectors by using few shot set from validation dataset? Or are you extending the model by modifying the last layer and finetuning or something else?

Thanks!

**Comment by dvornikita** [comment]
I am glad you made it work.

As for validation and test, we only use the feature extractor CNN (with no
fully-connected layer in the end) and build a prototype classifier on the
obtained features. You can read about it in Section 3 of the original paper.

**Comment by shivamsaboo17** [comment]
Thanks for clarifying, will look at the paper for more details!
