### ISSUE TITLE
RAM usage increasing continuously as training progress

### ISSUE THREAD

**Issue by shivamsaboo17** [dvornikita/fewshot_ensemble#4]
My CPU RAM (not GPU) usage is increasing continuously as training progresses. When training on mini-imagenet it starts from 5 gb and continues to increase beyond 16 gb which is the max. RAM that I have hence system crashes.

Is this the expected behavior (increased RAM utilization after every iteration?). If so, how can I fix the issue?

**Comment by shivamsaboo17** [comment]
I turned off memoization=False in dataset which I think is storing entire dataset in memory and things look better now. I hope this is the correct fix and doesn't affect other things in the code

**Comment by dvornikita** [comment]
Hi, I'm glad you managed your issue. Having the whole dataset in memory speeds up training/testing, however not possible when working with large datasets. What dataset are you experimenting with right now?

**Comment by shivamsaboo17** [comment]
Yes the memoization indeed speeds up the training/testing and is a good feature for smaller datasets but i had limited RAM available hence had to turn it off :)

I was working with custom dataset with around 0.2M images
